FJNR-inc/Blitz-Website

src/app/app.module.ts, src/app/components/nt-header/nt-header-sub/nt-header-sub.component.html, src/app/components/nt-header/nt-header-sub/nt-header-sub.component.scss, src/app/components/nt-header/nt-header-sub/nt-header-sub.component.spec.ts, src/app/components/nt-header/nt-header-sub/nt-header-sub.component.ts, src/app/components/nt-header/nt-header.component.html, src/app/components/nt-header/nt-header.component.scss, src/app/components/nt-header/nt-header.component.ts
| Tickets (_issues_) concerned               | [TV-8](https://fjnr-inc.atlassian.net/browse/TV-8)
---
Refactor of the design of NavBar
...
=> [WIP] New navbar design

.gitignore, package.json
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | [TV-179]
---
command line for generate translate file
update package.json file
...
-  [X] My branch name respect the standard defined in `CONTRIBUTING.md`
[TV-179]: https://fjnr-inc.atlassian.net/browse/TV-179
=> update generate translate file command

src/app/components/pages/retirement/retirement-list/retirement-list-item/retirement-list-item.component.html, src/app/components/pages/retirement/retirement-list/retirement-list-item/retirement-list-item.component.ts
| Tickets (_issues_) concerned               | [https://fjnr-inc.atlassian.net/jira/software/projects/TV/boards/2?selectedIssue=TV-186]
---
alert is only displayed when user is not connected
...
...
=> fix alert in retirement list

src/app/components/pages/validate-email/validate-email.component.html, src/app/components/pages/validate-email/validate-email.component.ts
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | [TV-187]
---
add loader in validation token page
by adding a loader component in validation token page
=> add loader in validation token page

src/app/components/pages/admin/period/period.component.html, src/app/components/pages/admin/period/period.component.ts
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | [TV-192]
---
plus possible de modifier l'option repeat pour les rédactions
en ajoutant une condition sur le bouton qui active l'option pendant le mode d'edition
...
[TV-192]: https://fjnr-inc.atlassian.net/browse/TV-192
=> disabled repeat timeslot on edit form

src/app/components/pages/reservation-page/reservation-page.component.ts, src/app/models/timeSlot.ts
| Type of contribution ?                      | [Fix]
| Tickets (_issues_) concerned               | [https://fjnr-inc.atlassian.net/jira/software/projects/TV/boards/2?selectedIssue=TV-194]
---
...
...
...
=> reservation-page use billing_price instead of price

src/app/components/pages/admin/coupons/coupons-creation/coupons-creation.component.ts, src/app/components/pages/admin/retreat/retreat.component.ts, src/app/components/pages/profile/profile-retreats/profile-retreats.component.html, src/app/components/pages/profile/profile-retreats/profile-retreats.component.ts, src/app/components/pages/retreat/retreat-list/retreat-list-item/retreat-list-item.component.ts, src/app/components/pages/retreat/retreat-list/retreat-list.component.ts, src/app/components/table/table-retreat-reservations/table-retreat-reservations.component.ts, src/app/models/cart.ts, src/app/models/coupon.ts, src/app/models/retreatReservation.ts, src/app/models/retreatWaitingQueue.ts, src/app/models/retreatWaitingQueueNotification.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.ts
---
Rename reference of `retirement` from the API communication to `retreat`
Manual renaming
None
=> rename reference to retirement coming from API

src/app/components/pages/profile/profile-retreats/profile-retreats.component.ts
| Type of contribution ?                      | [Fix]
| Tickets (_issues_) concerned               | [https://fjnr-inc.atlassian.net/jira/software/projects/TV/boards/2?selectedIssue=TV-151]
---
...
...
...
=> fix display error in reservation cancelation modale

src/app/components/pages/profile/profile-retreats/profile-retreats.component.ts
Reverts FJNR-inc/Blitz-Website#24
=> Revert "fix display error in reservation cancelation modale"

src/app/components/pages/login-page/login-page.component.html, src/app/components/pages/login-page/login-page.component.ts
| Type of contribution ?                      | [Fix]
| Tickets (_issues_) concerned               | [https://fjnr-inc.atlassian.net/jira/software/projects/TV/boards/2?selectedIssue=TV-147]
---
Disable login button while we are waiting for API response
...
...
=> Fix login button

src/app/components/pages/admin/timeslot/timeslot.component.ts
New release to fix ordering in workplace reservation
=> New release

src/app/components/my-table/my-table.component.html, src/app/components/my-table/my-table.component.ts, src/app/components/pages/admin/retreats/retreats.component.html, src/app/components/pages/admin/retreats/retreats.component.ts, src/app/services/retreat.service.ts
Fix my table check on download button
---
...
...
...
=> Add export reservations on retreat

src/app/components/pages/profile/profile-edit/profile-edit.component.ts
=> Fix default value for university to blank

src/app/components/table/table-retreat-reservations/table-retreat-reservations.component.ts, src/app/models/retreatReservation.ts, src/assets/i18n/fr.json
=> Add reservation date in admin panel

src/app/components/pages/admin/general/general.component.html, src/app/components/pages/admin/general/general.component.ts
=> Remove stats in admin panel for volunteer

src/app/components/pages/admin/retreat-invitation/retreat-invitation.component.ts
=> Reset list coupon when refresh

package.json
=> Add npm deploy command

deploy/index.html
=> release 3.1.0

src/app/models/orderLine.ts
=> Fix option undefined in order data

src/app/components/pages/payment-flow/payment-flow-membership/payment-flow-membership.component.html, src/app/components/pages/payment-flow/payment-flow-membership/payment-flow-membership.component.ts, src/app/components/shared/cart-payment/cart-payment.component.ts
=> Fix payment flow

src/app/components/pages/profile/profile-stats/profile-stats.component.html, src/app/components/pages/profile/profile-subscription/profile-subscription.component.html, src/assets/i18n/fr.json
---
Add link on profile page to help user renew his membership
Add conditionnal link on profile page
...
=> add link on profile page to renew membership

src/app/app.module.ts, src/app/components/pages/politics/politics.component.html, src/app/components/pages/politics/politics.component.scss, src/app/components/pages/politics/politics.component.ts
---
Add policy page to see policy of the organization
Add a component for the page
Create URL on it
=> add page for policy

src/app/components/pages/membership-subscription/membership-subscription.component.ts
=> fix end date if there are no membership

src/app/components/pages/membership-subscription/membership-subscription.component.ts
=> Manage case where membership end before today

src/app/components/pages/payment-flow/payment-flow-confirmation/payment-flow-confirmation.component.ts, src/app/components/pages/payment-flow/payment-flow-mode/payment-flow-mode.component.ts, src/assets/i18n/fr.json
=> Fix value of card when still not added to the profile

src/app/components/nt-wizzard/nt-wizzard.component.ts, src/app/components/pages/membership-subscription/membership-subscription.component.ts, src/app/components/pages/payment-flow/payment-flow.component.ts, src/app/services/my-cart/my-cart.service.ts
| Type of contribution ?                      | Features
---
...
...
...
=> Link membership flow to payment flow

src/app/components/pages/admin/retreat-invitation/retreat-invitation.component.ts, src/app/components/pages/hidden-retreat/hidden-retreat.component.html, src/app/components/pages/hidden-retreat/hidden-retreat.component.scss, src/app/components/shared/alert/alert.component.scss, src/app/components/shared/retreat-preview/retreat-preview.component.ts, src/app/models/RetreatInvitation.ts, src/assets/i18n/fr.json
display right number of seat
| Type of contribution ?                      | Features, Documentation
---
...
...
...
=> Add button to reserve seat in invitation and

src/app/components/pages/payment-flow/payment-flow-confirmation/payment-flow-confirmation.component.html, src/app/components/pages/payment-flow/payment-flow-confirmation/payment-flow-confirmation.component.ts, src/app/models/cart.ts
=> Change payment button if there are only timeslot in it

src/app/components/pages/payment-flow/payment-flow.component.ts
---
add payment flow conditions
...
...
=> add payment flow conditions

src/app/components/pages/payment-flow/payment-flow-membership/payment-flow-membership.component.html, src/app/components/pages/payment-flow/payment-flow-wizard/payment-flow-wizard.component.ts, src/app/components/pages/payment-flow/payment-flow.component.ts, src/app/models/cart.ts, src/app/services/my-cart/my-cart.service.ts
=> Fix condition dor step in payment flow

src/app/components/shared/cart-summary/cart-summary.component.html, src/app/components/shared/cart-summary/cart-summary.component.scss, src/app/components/shared/cart-summary/cart-summary.component.ts, src/app/services/my-cart/my-cart.service.ts
=> add button to allow user to clean the cart

src/app/components/pages/payment-flow/payment-flow-informations/payment-flow-informations.component.html, src/app/components/pages/payment-successful/payment-successful.component.html
=> update text payment validation page en retreat info

src/app/components/pages/admin/retreat-invitation/retreat-invitation.component.ts
=> Fix type of reserve_seat in form

src/app/components/shared/retreat-preview/retreat-preview.component.ts
=> fix condition to display waiting list

src/app/components/pages/payment-flow/payment-flow-bourse/payment-flow-bourse.component.ts, src/app/components/pages/payment-flow/payment-flow.component.ts, src/app/models/retreat.ts, src/app/services/my-cart/my-cart.service.ts
| Type of contribution ?                      |  Features
---
The stepper is now dynamic in fonction of element added or removed from the cart
fix error in init of retreat object
...
...
=> Stepper dynamic

src/app/components/my-table/my-table.component.html, src/app/components/my-table/my-table.component.ts, src/app/components/nt-header/nt-header.component.ts, src/assets/i18n/fr.json, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.ts
=> Fix default workplace, calendar missing translate and table translate

src/app/components/shared/paysafe-form/paysafe-form.component.ts, src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | [TV-265](https://fjnr-inc.atlassian.net/browse/TV-265)
---
Add placeholder on expiry date field when adding new credit card on payment-flow
Add support I18N, create new value
=> add placeholder for new card expiration date

src/app/components/pages/payment-successful/payment-successful.component.html, src/app/components/pages/payment-successful/payment-successful.component.ts
| Tickets (_issues_) concerned               | [TV-269](https://fjnr-inc.atlassian.net/browse/TV-269)
---
Change redirection after payment-flow
Just change the name of the function to redirect and the link in target
Can't do
=> fix redirection after payment-flow

src/app/components/nt-header/nt-header.component.ts
| Type of contribution ?                      | Documentation
| Tickets (_issues_) concerned               | [TV-277](https://fjnr-inc.atlassian.net/browse/TV-277)
---
Remove item from main nav
Remove the two items from the structure defined to populate the main nav
=> remove items from main-nav

src/app/components/pages/payment-flow/payment-flow-confirmation/payment-flow-confirmation.component.html
| Tickets (_issues_) concerned               | [TV-267](https://fjnr-inc.atlassian.net/browse/TV-267)
---
Add text for politics
Fix position of text in the html tag
=> fix text for politics in payment-flow confirmation

src/app/components/nt-header/nt-header.component.html
| Tickets (_issues_) concerned               | [TV-273](https://fjnr-inc.atlassian.net/browse/TV-273)
---
Close the nav when clicking on profile nav button in responsive mode
Call the toogle function on profile button click
None
=> toogle responsive nav when click on profile

src/app/components/pages/admin/retreat/retreat.component.html, src/app/components/pages/admin/timeslot/timeslot.component.html, src/app/components/pages/admin/timeslot/timeslot.component.scss, src/app/components/pages/admin/timeslot/timeslot.component.ts, src/app/models/cart.ts, src/assets/i18n/fr.json
---
Allow admin to create reservation to timeslot in place of user from Admin panel
Create a button on timeslot admin page
Create a modal to select user
Refactor cart to allow target_user option
Refactor cart to allow bypass_payment option
...
=> allow admin to create reservation to timeslot

src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | [TV-266](https://fjnr-inc.atlassian.net/browse/TV-266)
---
Fix typo
Just change i18n
None
=> fix feminin

src/app/components/pages/calendar/calendar.component.scss, src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | https://fjnr.freshdesk.com/a/tickets/167
---
...
...
=> Change NUIT to SOIR, and text orientation

src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | [Zendesk 178](https://fjnr.freshdesk.com/a/tickets/178)
---
Change text for additional user
Just change the i18n files
None
=> change text additional info retreat

src/app/components/shared/retreat-preview/retreat-preview.component.ts, src/app/services/my-notification/my-notification.service.ts
| Tickets (_issues_) concerned               |  https://fjnr.freshdesk.com/a/tickets/198
---
...
...
...
=> Change modal to notification for wait queue position

src/app/components/shared/authentication-panel/authentication-panel.component.html
=> Hotfix register link

tsconfig.json
=> Change es2015 to es5

src/app/components/pages/home-page/home-page.component.ts
=> Redirect to profile if logged

src/app/components/pages/admin/retreats/retreats.component.ts, src/app/services/retreat.service.ts
---
Revert order of retreat on admin panel list
Add ordering filter on service
None
=> revert order of retreat on admin panel

src/assets/scss/_reset.scss, src/assets/scss/_site.scss
---
Fix usage of typo
Change the reset scss file since it was more precise and took precedence on other scss file.
None
=> fix typo usage

src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/components/pages/admin/alert-modal-edit/alert-modal-edit.component.html, src/app/components/pages/admin/alert-modal-edit/alert-modal-edit.component.scss, src/app/components/pages/admin/alert-modal-edit/alert-modal-edit.component.spec.ts, src/app/components/pages/admin/alert-modal-edit/alert-modal-edit.component.ts, src/app/components/shared/ckeditor-container/ckeditor-container.component.ts, src/app/layouts/admin-layout/admin-layout.component.ts, src/assets/i18n/fr.json
=> Add ckeditor in alert modal

src/app/app.module.ts, src/app/components/pages/newsletter/newsletter-footer/newsletter-footer.component.html, src/app/components/pages/newsletter/newsletter-footer/newsletter-footer.component.scss, src/app/components/pages/newsletter/newsletter-footer/newsletter-footer.component.ts, src/app/components/pages/newsletter/newsletter-inscription/newsletter-inscription.component.html, src/app/components/pages/newsletter/newsletter-inscription/newsletter-inscription.component.scss, src/app/components/pages/newsletter/newsletter-inscription/newsletter-inscription.component.ts, src/app/components/pages/newsletter/newsletter-success/newsletter-success.component.html, src/app/components/pages/newsletter/newsletter-success/newsletter-success.component.scss, src/app/components/pages/newsletter/newsletter-success/newsletter-success.component.ts, src/app/components/shared/button/button.component.html, src/app/components/shared/button/button.component.scss, src/app/components/shared/button/button.component.ts, src/app/components/shared/form/form.component.ts, src/app/components/shared/link/link.component.html, src/app/components/shared/link/link.component.scss, src/app/components/shared/link/link.component.ts, src/app/layouts/new-layout/new-layout.component.ts, src/app/models/newsletterInscription.ts, src/app/models/user.ts, src/app/services/newsletter.service.ts, src/assets/i18n/fr.json, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.ts
=> Add newsletter inscription

src/app/components/pages/hidden-retreat/hidden-retreat.component.scss, src/app/components/pages/home-page/home-page.component.scss, src/app/components/pages/newsletter/newsletter-footer/newsletter-footer.component.scss, src/app/components/pages/reservation-page/reservation-page.component.scss, src/app/components/pages/retreat/retreat-reservation/retreat-reservation.component.scss, src/app/layouts/light-layout/light-layout.component.ts
=> Fix responsive footer and home page

src/app/app.module.ts, src/app/components/pages/hidden-retreat/hidden-retreat.component.html, src/app/components/pages/hidden-retreat/hidden-retreat.component.ts, src/app/components/pages/newsletter/newsletter-footer/newsletter-footer.component.html, src/app/components/pages/newsletter/newsletter-footer/newsletter-footer.component.scss, src/app/components/pages/reservation-page/reservation-page.component.html, src/app/components/pages/reservation-page/reservation-page.component.scss, src/app/components/pages/reservation-page/reservation-page.component.ts, src/app/components/pages/retreat/retreat-reservation/retreat-reservation.component.html, src/app/components/pages/retreat/retreat-reservation/retreat-reservation.component.scss, src/app/components/pages/retreat/retreat-reservation/retreat-reservation.component.ts, src/app/components/shared/product-selector-panel/product-selector-panel.component.ts, src/app/components/shared/right-panel-container/right-panel-container.component.html, src/app/components/shared/right-panel-container/right-panel-container.component.scss, src/app/components/shared/right-panel-container/right-panel-container.component.ts, src/app/layouts/light-layout/light-layout.component.scss, src/app/layouts/light-layout/light-layout.component.ts, src/app/layouts/new-layout/new-layout.component.scss, src/app/layouts/new-layout/new-layout.component.ts, src/app/services/right-panel.service.ts
| Type of contribution ?                      | Features
---
- Remove left panel from "sub" component
- Add new left panel component in new-layout and light-layout
- add service to manage communication with left panel
- update responsive of footer
...
=> Add right panel management with service

src/app/components/pages/workplace-list/workplace-list.component.ts
| Tickets (_issues_) concerned               | None (direct request from raphaelle on Slack)
---
Remove actual pilot workplace on the platform
Remove item of the list of pilot
=> hide pilot place

src/app/components/pages/profile/profile-retreats/profile-retreats.component.ts, src/app/components/pages/retreat/retreat-list/retreat-list.component.ts, src/app/components/pages/retreat/retreat-reservation/retreat-reservation.component.ts, src/app/services/retreat.service.ts
---
Change filter name to be in sync with new API endpoints
Just changed the API service and usages
None
=> fix filter date on retreat

src/app/components/pages/payment-flow/payment-flow-confirmation/payment-flow-confirmation.component.html
---
Add title on cancellation policies modal
Add a text
=> add title cancellation on modal

src/app/components/pages/admin/period/period.component.ts, src/app/components/pages/calendar/calendar.component.ts, src/app/components/pages/reservation-page/reservation-page.component.ts, src/app/models/calendar.ts, src/app/models/timeSlot.ts
=> change reservations for nb_reservations_active

src/app/components/pages/admin/timeslot/timeslot.component.ts, src/app/components/pages/calendar/calendar.component.ts, src/app/components/pages/profile/profile-timeslots/profile-timeslots.component.ts, src/app/components/pages/reservation-page/reservation-page.component.ts, src/app/models/calendar.ts, src/app/models/timeSlot.ts
=> replace timeslot.user for is_reserved

src/app/components/pages/admin/user-page/user-page.component.ts
=> limit reservation list size in admin

src/app/components/pages/home-page/home-page.component.html
| Tickets (_issues_) concerned               | [TV-334](https://fjnr-inc.atlassian.net/browse/TV-334)
---
Just hardcoded link on Homepage ckeditor
Manually
No
=> change url ckeditor homepage

src/app/components/pages/payment-flow/payment-flow-membership/payment-flow-membership.component.html, src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | [TV-344](https://fjnr-inc.atlassian.net/browse/TV-344)
---
Change text has requested
Update translation file, hide second paragraphe, so if need in futur we can rallback it quickly
...
=> Update text membership step

src/app/components/pages/home-page/home-page.component.html
| Type of contribution ?                      |  Features
| Tickets (_issues_) concerned               | [TV-334](https://fjnr-inc.atlassian.net/browse/TV-334)
---
Change href url to https://www.thesez-vous.com/bourses.html
...
...
=> update link home page ckeditor

src/app/components/pages/admin/user-page/user-page.component.ts, src/app/components/pages/payment-flow/payment-flow-bourse/payment-flow-bourse.component.ts, src/app/components/pages/payment-flow/payment-flow-informations/payment-flow-informations.component.ts, src/app/components/pages/profile/profile-edit/profile-edit.component.ts, src/app/models/user.ts, src/app/services/newsletter.service.ts, src/app/services/user.service.ts
| Tickets (_issues_) concerned               | [TV-332](https://fjnr-inc.atlassian.net/browse/TV-332)
---
Update only `hide_newsletter` when hide newsletter
I create a new interface to manage only editable fields on user to  have a better indication of the current updated value
...
=> add control on user update

src/app/components/pages/payment-flow/payment-flow-confirmation/payment-flow-confirmation.component.html, src/app/components/pages/payment-flow/payment-flow-confirmation/payment-flow-confirmation.component.ts
| Tickets (_issues_) concerned               | [TV-342](https://fjnr-inc.atlassian.net/browse/TV-342)
---
Disable valdate button when creating order
...
...
=> disable validate order when processing

src/app/components/pages/home-page/home-page.component.html
=> home page open link in new page

src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | [TV-349](https://fjnr-inc.atlassian.net/browse/TV-349)
---
Changement de textes dans la section du coupon de bourse du panier
Changement dans le fichier de traduction du texte.
=> Text change for application coupon section

src/app/components/pages/hidden-retreat/hidden-retreat.component.ts
| Tickets (_issues_) concerned               | [Ticket 2407](https://redmine.fjnr.ca/issues/2407)
---
Add a condition to limit coupon message information
Just add a condition in the TS file
Not required
- Melanie will do the other points in an other ticket to rampup
=> fix(retreat-invitation): hide coupon message when not needed

src/app/components/pages/hidden-retreat/hidden-retreat.component.ts
https://redmine.fjnr.ca/issues/2443
=> fix usage of null coupon in hidden retreat

src/app/components/my-table/my-table.component.html, src/app/components/my-table/my-table.component.ts, src/app/components/pages/admin/retreats/retreats.component.html, src/app/components/pages/admin/retreats/retreats.component.ts, src/app/services/retreat.service.ts
| Type of contribution ?                      | Features
| Tickets (_issues_) concerned               | [Ticket 2521](https://redmine.fjnr.ca/issues/2521)
---
Added a search bar
Added a button to open selected item in new tab
nothing special
=> Add search bar and button for new tab

src/app/components/pages/payment-flow/payment-flow-bourse/payment-flow-bourse.component.ts
| Tickets (_issues_) concerned               | [Ticket 2667](https://redmine.fjnr.ca/issues/2667)
---
Remove bourse fields in management of cart
Nothing special
=> remove profile field no more required

src/app/components/pages/admin/retreats/retreats.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.ts
=> New feature

src/app/components/my-table/my-table.component.html
---
Manage empty search bar
Replace (keypress) event by (ngModelChange) event
No design changes
=> Fix search bar change

src/app/components/pages/admin/retreat/retreat.component.ts, src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | [2523](https://redmine.fjnr.ca/issues/2523)
---
Add display_start_time field on admin panel
Just add the new field
=> add display_start_time on admin panel form

src/app/components/pages/profile/profile-reservation-open/profile-reservation-open.component.ts, src/app/services/retreat-reservation.service.ts
| Type of contribution ?                      | Features
| Tickets (_issues_) concerned               | [Ticket 2518](https://redmine.fjnr.ca/issues/2518)
---
Add log of activities before redirect to videoconference link
No
No visual
=> log activity of retreat before redirect

src/app/components/pages/payment-flow/payment-flow.component.ts, src/app/models/cart.ts, src/app/services/my-cart/my-cart.service.ts
| Tickets (_issues_) concerned               | [Ticket 2838](https://redmine.fjnr.ca/issues/2838)
---
Add section bourse on payment flow when package in cart
Nothing special, followed the same logic as the existing
Nothing changed
=> add bourses section on packages

src/app/components/pages/admin/retreat/retreat.component.ts, src/app/models/retreat.ts, src/assets/i18n/en.json, src/assets/i18n/fr.json
| Tickets (_issues_) concerned               | [2979](https://redmine.fjnr.ca/issues/2979)
=> add number of tomatoes on retreat form
